/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi_1sem.screens;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import pi_1sem.modelo.jogo.Materia;
import pi_1sem.persistencia.jogo.MateriaDAO;
import pi_1sem.persistencia.jogo.PerguntaAlternativaDAO;
import pi_1sem.modelo.jogo.PerguntaAlternativa;
import pi_1sem.persistencia.jogo.AlternativaDAO;
import pi_1sem.persistencia.jogo.PerguntaDAO;

/**
 *
 * @author charl
 */
public class EditarPergunta extends javax.swing.JFrame {
    private String filtroAtual = "Todas";
    /**
     * Creates new form EditarPergunta
     */
    public EditarPergunta() {
        initComponents();
        listarPerguntas(this.filtroAtual);
        capturarAltercoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        todasPerguntasTable = new javax.swing.JTable();
        excluirButton = new javax.swing.JButton();
        adicionarPerguntaButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        todasPerguntasTable.setShowGrid(true);
        todasPerguntasTable.setGridColor(java.awt.Color.GRAY);
        todasPerguntasTable.setRowHeight(30);
        todasPerguntasTable.setBackground(new java.awt.Color(204, 204, 204));
        todasPerguntasTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        todasPerguntasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pergunta", 
                "Enuciado", 
                "Materia ▼", 
                "Dificuldade", 
                "Opção A", 
                "Opção B", 
                "Opção C", 
                "Opção D", 
                "Alternativa Correta",
                "ID Alternaativa A",
                "ID Alternaativa B",
                "ID Alternaativa C",
                "ID Alternaativa D",
                "ID Alternaativa Correta"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0 && column < 9;
            }
        });
        for (int i = 1; i < todasPerguntasTable.getColumnCount(); i++) {
            javax.swing.table.TableColumn column = todasPerguntasTable.getColumnModel().getColumn(i);
            if (column.getCellEditor() instanceof javax.swing.DefaultCellEditor) {
                ((javax.swing.DefaultCellEditor) column.getCellEditor()).setClickCountToStart(2);
            }
        }
        jScrollPane1.setViewportView(todasPerguntasTable);
        todasPerguntasTable.setComponentPopupMenu(criaMateriaPopup());
        JTableHeader header = todasPerguntasTable.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Converter o ponto de clique para o sistema de coordenadas do cabeçalho
                Point point = e.getPoint();
                int colIndex = header.columnAtPoint(point);
                
                if (colIndex >= 0) {
                    String columnName = todasPerguntasTable.getColumnName(colIndex);
                    
                    if ("Materia ▼".equals(columnName)) { // Verifique o nome exato da coluna
                        showFilterDialog();
                    }
                }
            }
        });

        excluirButton.setBackground(new java.awt.Color(255, 51, 51));
        excluirButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        excluirButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirButton.setText("Excluir ");
        excluirButton.setBorder(null);

        adicionarPerguntaButton.setBackground(new java.awt.Color(0, 102, 255));
        adicionarPerguntaButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        adicionarPerguntaButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarPerguntaButton.setText("Adicionar Pergunta");
        adicionarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPerguntaButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POLIEDRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setText("Editar Pergunta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPerguntaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPerguntaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPergunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirButton;
    private javax.swing.JButton adicionarPerguntaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable todasPerguntasTable;
    // End of variables declaration//GEN-END:variables

    private void listarPerguntas(String filtroMateria) {
        if (filtroMateria.equals("Todas")){
            try{
                var perguntaAlternativadao= new PerguntaAlternativaDAO();
                var perguntas= perguntaAlternativadao.listarPerguntasAlternativas();
                listarBasico(perguntas);
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao listar as perguntas");
            }
        }
        else{
            try{
                var perguntaAlternativadao= new PerguntaAlternativaDAO();
                var perguntas= perguntaAlternativadao.listarPerguntasAlternativasExpecificas(filtroMateria);
                this.filtroAtual= filtroMateria;
                listarBasico(perguntas);
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao listar as perguntas");
            }
        }
    }
    private void listarBasico (List<PerguntaAlternativa> perguntas){
        DefaultTableModel model = (DefaultTableModel) todasPerguntasTable.getModel();
        model.setRowCount(0);

        String alternativaCorreta= "";
        int idAltCorreta= 0;

        for(int i = 0; i < perguntas.size(); i += 4){
            var id= perguntas.get(i).getPergunta().getId();
            var enunciado= perguntas.get(i).getPergunta().getEnunciado();
            var materia= perguntas.get(i).getPergunta().getMateria().getNome();
            var nivel= perguntas.get(i).getPergunta().getNivel();
            var alternativaA = perguntas.get(i).getAlternativa().getTexto();
            var alternativaB = perguntas.get(i+1).getAlternativa().getTexto();
            var alternativaC = perguntas.get(i+2).getAlternativa().getTexto();
            var alternativaD = perguntas.get(i+3).getAlternativa().getTexto();

            var idAltA = perguntas.get(i).getAlternativa().getId();
            var idAltB = perguntas.get(i+1).getAlternativa().getId();
            var idAltC = perguntas.get(i+2).getAlternativa().getId();
            var idAltD = perguntas.get(i+3).getAlternativa().getId();

            for(int j = i; j < (i+4); j++){
                if(perguntas.get(j).isCorreta() == true){
                    alternativaCorreta = perguntas.get(j).getAlternativa().getLetra();
                    idAltCorreta = perguntas.get(j).getAlternativa().getId();
                }
            }
            model.addRow(new Object[]{
                id, 
                enunciado, 
                materia, 
                nivel, 
                alternativaA, 
                alternativaB, 
                alternativaC, 
                alternativaD, 
                alternativaCorreta,
                idAltA,
                idAltB,
                idAltC,
                idAltD,
                idAltCorreta

            });
        }
        if(todasPerguntasTable.getColumnCount() > 9){
            ocultarColunasIds();
        }
    }
    private JPopupMenu criaMateriaPopup() {
        var popupMenu = new JPopupMenu();
        var filterMenuItem = new JMenuItem("Filtrar por Matéria");
        filterMenuItem.addActionListener(e -> showFilterDialog());
        popupMenu.add(filterMenuItem);
        return popupMenu;
    }
    private void showFilterDialog() {
        JDialog filterDialog = new JDialog(this, "Filtrar Matérias", true);
        filterDialog.setLayout(new BorderLayout());
        
        // Painel principal
        JPanel panel = new JPanel(new GridLayout(3, 1, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Combo box de matérias
        JLabel label = new JLabel("Selecione a matéria:");
        JComboBox<String> materiasComboBox = new JComboBox<>();
        materiasComboBox.addItem("Todas");
        
        try {
            var materiadao= new MateriaDAO();
            var materias= materiadao.listarMaterias();
            for (Materia materia : materias) {
                materiasComboBox.addItem(materia.getNome());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Botões
        JButton applyButton = new JButton("Aplicar Filtro");
        applyButton.addActionListener(e -> {
            listarPerguntas((String) materiasComboBox.getSelectedItem());
            filterDialog.dispose();
        });
        
        JButton cancelButton = new JButton("Cancelar");
        cancelButton.addActionListener(e -> filterDialog.dispose());
        
        // Adicionar componentes
        panel.add(label);
        panel.add(materiasComboBox);
        
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(cancelButton);
        buttonPanel.add(applyButton);
        
        filterDialog.add(panel, BorderLayout.CENTER);
        filterDialog.add(buttonPanel, BorderLayout.SOUTH);
        
        filterDialog.pack();
        filterDialog.setLocationRelativeTo(this);
        filterDialog.setVisible(true);
    }
    private void capturarAltercoes(){
        var model = (DefaultTableModel) todasPerguntasTable.getModel();

        model.removeTableModelListener(this::handleTableUpdate);
        model.addTableModelListener(this::handleTableUpdate);
    }
    private void handleTableUpdate(TableModelEvent e) {
        if (e.getType() != TableModelEvent.UPDATE || e.getColumn() < 1) return;
        
        int row = e.getFirstRow();
        int col = e.getColumn();
        
        if (row < 0 || row >= todasPerguntasTable.getRowCount()) return;
    
        var valorAlterado = todasPerguntasTable.getModel().getValueAt(row, col).toString();
        if(valorAlterado.equals("")){
            JOptionPane.showMessageDialog(null, "Não é possível alterar para um campo vazio");
            return;
        }
        
        var id = Integer.parseInt(todasPerguntasTable.getModel().getValueAt(row, 0).toString());

        if (col == 1){
            var enunciado = valorAlterado;
            try{
                var perguntadao = new PerguntaDAO();
                perguntadao.editarPergunta(enunciado, id);
                JOptionPane.showMessageDialog(null, "Enunciado alterado com sucesso");
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao editar a pergunta");
            }
        }

        // Altera todas as colunas de alternativa menos a alternativa correta
        if (col >= 4 && col <= 7) {
            var altIndex= col - 4;

            int posAltCol = 9 + altIndex; // Colunas 9,10,11,12 correspondem às alternativas
            int idAlternativa = (int) todasPerguntasTable.getModel().getValueAt(row, posAltCol);

            JOptionPane.showMessageDialog(null, "alteracao sucesso " + idAlternativa);
            try{
                var alternativadao = new AlternativaDAO();
                alternativadao.editarAlternativa(valorAlterado, id, idAlternativa);

                JOptionPane.showMessageDialog(null, "a pergunta foi alterada com sucesso");            
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao editar alternativa");
            }
        }

        //Altera a alternativa correta
        if (col == 8 ) {
            var valorAlteradoMaiusculo=valorAlterado.toUpperCase();

            if (valorAlteradoMaiusculo.equals("A") || valorAlteradoMaiusculo.equals("B") || valorAlteradoMaiusculo.equals("C") || valorAlteradoMaiusculo.equals("D")) {
                int idNovaAlternativaCorreta=0;
                if(valorAlteradoMaiusculo.equals("A")){
                    idNovaAlternativaCorreta = (int) todasPerguntasTable.getModel().getValueAt(row, 9);
                }
                else if(valorAlteradoMaiusculo.equals("B")){
                    idNovaAlternativaCorreta = (int) todasPerguntasTable.getModel().getValueAt(row, 10);
                }
                else if(valorAlteradoMaiusculo.equals("C")){
                    idNovaAlternativaCorreta = (int) todasPerguntasTable.getModel().getValueAt(row, 11);
                }
                else if(valorAlteradoMaiusculo.equals("D")){
                    idNovaAlternativaCorreta = (int) todasPerguntasTable.getModel().getValueAt(row, 12);
                }

                int idAntigaAlternativaCorreta = (int) todasPerguntasTable.getModel().getValueAt(row, 13);
    
                try{
                    var alternativadao = new AlternativaDAO();
                    alternativadao.removerAlternativaCorreta(id, idAntigaAlternativaCorreta);
                    alternativadao.adicionarAlternativaCorreta(id, idNovaAlternativaCorreta);
                    
                    listarPerguntas(filtroAtual);
                   

                    JOptionPane.showMessageDialog(null, "a alternativa correta foi alterada com sucesso");
                }
                catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao editar alternativa correta");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "ERRO!!! alteração não salva no banco. Adicione como alternativa correta algum valor que esteja no intervalo de A até D");
            }
        }
    }
    private void ocultarColunasIds() {
        todasPerguntasTable.removeColumn(todasPerguntasTable.getColumnModel().getColumn(13)); // ID Pergunta
        todasPerguntasTable.removeColumn(todasPerguntasTable.getColumnModel().getColumn(12)); // ID Alt D
        todasPerguntasTable.removeColumn(todasPerguntasTable.getColumnModel().getColumn(11)); // ID Alt C
        todasPerguntasTable.removeColumn(todasPerguntasTable.getColumnModel().getColumn(10)); // ID Alt B
        todasPerguntasTable.removeColumn(todasPerguntasTable.getColumnModel().getColumn(9)); // ID Alt A
    }
}
