package pi_1sem.screens;

import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charl
 */
public class Perguntas extends javax.swing.JFrame {

    /**
     * Creates new form Perguntas1_2
     */
    public Perguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DicaButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        enviarButton = new javax.swing.JButton();
        opcaoCToggleButton = new javax.swing.JToggleButton();
        opcaoAToggleButton = new javax.swing.JToggleButton();
        opcaoBToggleButton = new javax.swing.JToggleButton();
        opcaoDToggleButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 133, 224));

        DicaButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\charl\\Downloads\\PI Mauá\\lampada 1.6.png")); // NOI18N
        DicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicaButtonActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\charl\\Downloads\\PI Mauá\\imagem do poliedro 1.3.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jButton7.setText("Parar");

        enviarButton.setBackground(new java.awt.Color(51, 204, 0));
        enviarButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        opcaoCToggleButton.setBackground(new java.awt.Color(64, 133, 224));
        buttonGroup1.add(opcaoCToggleButton);
        opcaoCToggleButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        opcaoCToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        opcaoCToggleButton.setText("C-)Resposta");

        opcaoAToggleButton.setBackground(new java.awt.Color(64, 133, 224));
        buttonGroup1.add(opcaoAToggleButton);
        opcaoAToggleButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        opcaoAToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        opcaoAToggleButton.setText("A-)Resposta");

        opcaoBToggleButton.setBackground(new java.awt.Color(64, 133, 224));
        buttonGroup1.add(opcaoBToggleButton);
        opcaoBToggleButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        opcaoBToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        opcaoBToggleButton.setText("B-)Resposta");

        opcaoDToggleButton.setBackground(new java.awt.Color(64, 133, 224));
        buttonGroup1.add(opcaoDToggleButton);
        opcaoDToggleButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        opcaoDToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        opcaoDToggleButton.setText("D-)Resposta");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1:Pergunta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(DicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcaoBToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcaoAToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcaoDToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcaoCToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcaoCToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcaoAToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcaoBToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcaoDToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicaButtonActionPerformed

    // 1. Lista de todas as respostas erradas (excluindo a correta)
   java.util.List<JToggleButton> respostasErradas = new java.util.ArrayList<>();
    
    // Supondo que 'opcaoCToggleButton' é a resposta correta
    JToggleButton respostaCorreta = opcaoCToggleButton; // Altere para o seu botão correto
    
    // Adiciona apenas as respostas erradas e visíveis à lista
    if (opcaoAToggleButton != respostaCorreta && opcaoAToggleButton.isVisible()) {
        respostasErradas.add(opcaoAToggleButton);
    }
    if (opcaoBToggleButton != respostaCorreta && opcaoBToggleButton.isVisible()) {
        respostasErradas.add(opcaoBToggleButton);
    }
    if (opcaoDToggleButton != respostaCorreta && opcaoDToggleButton.isVisible()) {
        respostasErradas.add(opcaoDToggleButton);
    }

    // 2. Calcula quantas esconder (metade das erradas, arredondando para baixo)
    int qtdParaEsconder = respostasErradas.size() / 2;

    // 3. Embaralha as respostas erradas aleatoriamente
    Collections.shuffle(respostasErradas);

    // 4. Esconde as respostas selecionadas
    for (int i = 0; i < qtdParaEsconder && i < respostasErradas.size(); i++) {
        respostasErradas.get(i).setVisible(false);
    }

    // 5. Atualiza a interface
    revalidate();
    repaint();

    // 6. Feedback para o usuário
    JOptionPane.showMessageDialog(this, 
        "Dica usada! " + qtdParaEsconder + " opção(ões) errada(s) foram removidas.",
        "Dica", 
        JOptionPane.INFORMATION_MESSAGE);

    // 7. Desabilita o botão da dica após o uso (opcional)
    DicaButton.setEnabled(false);

        
        
    }//GEN-LAST:event_DicaButtonActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
       
    // 1. Verifica qual resposta está selecionada
    JToggleButton respostaSelecionada = null;
    
    // Lista de todas as opções de resposta
    JToggleButton[] todasRespostas = {
        opcaoAToggleButton, 
        opcaoBToggleButton, 
        opcaoCToggleButton, 
        opcaoDToggleButton  // Adicione mais se necessário
    };
    
    // Procura qual está selecionada
    for (JToggleButton resposta : todasRespostas) {
        if (resposta.isSelected()) {
            respostaSelecionada = resposta;
            break;
        }
    }
    
    // 2. Verifica se alguma resposta foi selecionada
    if (respostaSelecionada == null) {
        JOptionPane.showMessageDialog(this, 
            "Selecione uma resposta antes de enviar!", 
            "Aviso", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 3. Define qual é a resposta correta (ajuste para o seu caso)
    JToggleButton respostaCorreta = opcaoCToggleButton; // Exemplo: C é a correta
    
    // 4. Verifica se acertou
    boolean acertou = (respostaSelecionada == respostaCorreta);
    
    // 5. Mostra o feedback visual
    if (acertou) {
        respostaSelecionada.setBackground(Color.GREEN);
        JOptionPane.showMessageDialog(this, 
            "✅ Resposta Correta!", 
            "Parabéns", 
            JOptionPane.INFORMATION_MESSAGE);
    } else {
        respostaSelecionada.setBackground(Color.RED);
        respostaCorreta.setBackground(Color.GREEN);
        JOptionPane.showMessageDialog(this, 
            "❌ Resposta Incorreta!\nA resposta correta é: " + respostaCorreta.getText(), 
            "Resultado", 
            JOptionPane.ERROR_MESSAGE);
    
    
    // 6. Desabilita todas as respostas após enviar (opcional)
    for (JToggleButton resposta : todasRespostas) {
        resposta.setEnabled(false);
    }
    
    // 7. Desabilita o botão de enviar (opcional)
    enviarButton.setEnabled(false);
}
        
        
        
        
        
        
    }//GEN-LAST:event_enviarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DicaButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton enviarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton opcaoAToggleButton;
    private javax.swing.JToggleButton opcaoBToggleButton;
    private javax.swing.JToggleButton opcaoCToggleButton;
    private javax.swing.JToggleButton opcaoDToggleButton;
    // End of variables declaration//GEN-END:variables
}
