package pi_1sem.screens;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import pi_1sem.modelo.jogo.Materia;
import pi_1sem.modelo.jogo.Partida;
import pi_1sem.modelo.jogo.Pergunta;
import pi_1sem.persistencia.jogo.PerguntaDAO;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charl
 */
public class Perguntas extends javax.swing.JFrame {

    /**
     * Creates new form Perguntas1_2
     */
    public Perguntas(Partida partida) {
        List<String>base= perguntaSelecionada(partida);
        initComponents(base);
        pararButton.setEnabled(partida.getPosicao() >= 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(List<String>base) {

        jPanel1 = new javax.swing.JPanel();
        DicajButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        perguntaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        alternativaDButton = new javax.swing.JButton();
        alternativaAButton = new javax.swing.JButton();
        alternativaCButton = new javax.swing.JButton();
        alternativaBButton = new javax.swing.JButton();
        pararButton = new javax.swing.JButton();
        enviarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 133, 224));

        DicajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicajButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        perguntaPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        perguntaPanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText(base.get(0));

        javax.swing.GroupLayout perguntaPanelLayout = new javax.swing.GroupLayout(perguntaPanel);
        perguntaPanel.setLayout(perguntaPanelLayout);
        perguntaPanelLayout.setHorizontalGroup(
            perguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(707, Short.MAX_VALUE))
        );
        perguntaPanelLayout.setVerticalGroup(
            perguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        alternativaDButton.setBackground(new java.awt.Color(64, 133, 224));
        alternativaDButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        alternativaDButton.setForeground(new java.awt.Color(255, 153, 0));
        alternativaDButton.setText(base.get(4));
        alternativaDButton.setBorder(null);

        alternativaAButton.setBackground(new java.awt.Color(64, 133, 224));
        alternativaAButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        alternativaAButton.setForeground(new java.awt.Color(255, 153, 0));
        alternativaAButton.setText(base.get(1));
        alternativaAButton.setBorder(null);

        alternativaCButton.setBackground(new java.awt.Color(64, 133, 224));
        alternativaCButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        alternativaCButton.setForeground(new java.awt.Color(255, 153, 0));
        alternativaCButton.setText(base.get(3));
        alternativaCButton.setBorder(null);

        alternativaBButton.setBackground(new java.awt.Color(64, 133, 224));
        alternativaBButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        alternativaBButton.setForeground(new java.awt.Color(255, 153, 0));
        alternativaBButton.setText(base.get(2));
        alternativaBButton.setBorder(null);

        pararButton.setBackground(new java.awt.Color(255, 0, 0));
        pararButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        pararButton.setText("Parar");
        pararButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararButtonActionPerformed(evt);
            }
        });

        enviarButton.setBackground(new java.awt.Color(51, 204, 0));
        enviarButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DicajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternativaBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alternativaDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(perguntaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(pararButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(alternativaAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(885, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(alternativaCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(882, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1056, Short.MAX_VALUE)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DicajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perguntaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(alternativaBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(alternativaDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pararButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(257, Short.MAX_VALUE)
                    .addComponent(alternativaAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(191, 191, 191)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(357, Short.MAX_VALUE)
                    .addComponent(alternativaCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(91, 91, 91)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(444, Short.MAX_VALUE)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DicajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicajButton1ActionPerformed
        
        // Esconde duas opções de resposta (por exemplo, C e D)
    alternativaDButton.setVisible(false); // Opção C
    alternativaAButton.setVisible(false); // Opção D
    
    // Atualiza a interface
    revalidate();
    repaint();
    
    // Opcional: Mostrar mensagem
    JOptionPane.showMessageDialog(this, "Duas opções foram removidas!");
        
        
    }//GEN-LAST:event_DicajButton1ActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void pararButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Tem certeza que deseja parar?");
        
    }//GEN-LAST:event_pararButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DicajButton1;
    private javax.swing.JButton alternativaAButton;
    private javax.swing.JButton alternativaBButton;
    private javax.swing.JButton alternativaCButton;
    private javax.swing.JButton alternativaDButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton pararButton;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel perguntaPanel;
    // End of variables declaration//GEN-END:variables

    private List<String> perguntaSelecionada(Partida partida) {
        String nivel;
        var questao= new ArrayList<String>();
        if (partida.getPosicao() <= 4){
            nivel = "fácil";
        }
        else if (partida.getPosicao() <= 8){
            nivel = "médio";
        }
        else if (partida.getPosicao() <= 12){
            nivel = "difícil";
        }
        else{
            nivel = null;
        }
        try{
            var perguntaDao = new PerguntaDAO();
            var banco= perguntaDao.bancoDeQuestoes(nivel, partida.getMateria());
    
            var tamanho= banco.size();
            int indexSorteado;
            do{
                int k= (int) (Math.random() * (tamanho/4));
                indexSorteado= 4 * k;
                if (!partida.getPerguntasSorteadas().contains(indexSorteado)){
                    partida.getPerguntasSorteadas().add(indexSorteado);

                    questao.add(banco.get(indexSorteado).getPergunta().getEnunciado());
                    questao.add(banco.get(indexSorteado).getAlternativa().getTexto());
                    questao.add(banco.get((indexSorteado+ 1)).getAlternativa().getTexto());
                    questao.add(banco.get((indexSorteado+ 2)).getAlternativa().getTexto());
                    questao.add(banco.get((indexSorteado+ 3)).getAlternativa().getTexto());
                    for(int j = indexSorteado; j < (indexSorteado+4); j++){
                        if(banco.get(j).isCorreta() == true){
                            questao.add(banco.get(j).getAlternativa().getTexto());
                        }
                    }
                    break;
                }
            } while(true);

            return questao;
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao selecionar a pergunta");
            return null;
        }
    }
}
