/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi_1sem.screens;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;

import pi_1sem.modelo.jogo.Alternativa;
import pi_1sem.modelo.jogo.Materia;
import pi_1sem.modelo.jogo.Pergunta;
import pi_1sem.modelo.jogo.PerguntaAlternativa;
import pi_1sem.modelo.participantes.Usuario;
import pi_1sem.persistencia.jogo.AlternativaDAO;
import pi_1sem.persistencia.jogo.MateriaDAO;
import pi_1sem.persistencia.jogo.PerguntaAlternativaDAO;
import pi_1sem.persistencia.jogo.PerguntaDAO;
import pi_1sem.persistencia.usuarios.UsuarioDAO;


/**
 *
 * @author charl
 */
public class TelaAdcionarPergunta extends javax.swing.JFrame {

    /**
     * Creates new form EditarPergunta
     */
    public TelaAdcionarPergunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        alterantivasButtonGroup = new javax.swing.ButtonGroup();
        alternativaBRadioButton = new javax.swing.JRadioButton();
        escolherMateriaComboBox = new javax.swing.JComboBox<>();
        alternativaCTextField = new javax.swing.JTextField();
        escolherDificuldadeComboBox = new javax.swing.JComboBox<>();
        alternativaBTextField = new javax.swing.JTextField();
        alternativaDTextField = new javax.swing.JTextField();
        alternativaATextField = new javax.swing.JTextField();
        alternativaDRadioButton = new javax.swing.JRadioButton();
        alternativaARadioButton = new javax.swing.JRadioButton();
        alternativaCRadioButton = new javax.swing.JRadioButton();
        perguntaTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        adicionarPerguntaButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POLIEDRO");

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alterantivasButtonGroup.add(alternativaBRadioButton);
        alternativaBRadioButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alternativaBRadioButton.setText("Alternativa B");
        getContentPane().add(alternativaBRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        escolherMateriaComboBox.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        try{
            var materiaDao= new MateriaDAO();
            var materias= materiaDao.listarMaterias();
                for (Materia materia : materias) {
                    escolherMateriaComboBox.addItem(materia.getNome());
                }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar materias no seletor");
        }
        escolherMateriaComboBox.setBorder(null);
        escolherMateriaComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escolherMateriaComboBox.setOpaque(true);
        getContentPane().add(escolherMateriaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 120, 40));

        alternativaCTextField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        alternativaCTextField.setBorder(null);
        
        getContentPane().add(alternativaCTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 260, 30));

        escolherDificuldadeComboBox.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        escolherDificuldadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fácil", "médio", "difícil"}));
            
        getContentPane().add(escolherDificuldadeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 500, 130, 40));

        alternativaBTextField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        alternativaBTextField.setBorder(null);
        
        getContentPane().add(alternativaBTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 260, 30));

        alternativaDTextField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        alternativaDTextField.setBorder(null);
        
        getContentPane().add(alternativaDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 260, 30));

        alternativaATextField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        alternativaATextField.setBorder(null);
        
        getContentPane().add(alternativaATextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 260, 30));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        jLabel13.setText("Dificuldade:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, 40));

        alterantivasButtonGroup.add(alternativaDRadioButton);
        alternativaDRadioButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alternativaDRadioButton.setText("Alternativa D");
        getContentPane().add(alternativaDRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        alterantivasButtonGroup.add(alternativaARadioButton);
        alternativaARadioButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alternativaARadioButton.setText("Alternativa A");
        
        getContentPane().add(alternativaARadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        alterantivasButtonGroup.add(alternativaCRadioButton);
        alternativaCRadioButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alternativaCRadioButton.setText("Alternativa C");
        getContentPane().add(alternativaCRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 383, -1, 60));

        perguntaTextField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        perguntaTextField.setBorder(null);
        
        getContentPane().add(perguntaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 520, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POLIEDRO");

        jLabel10.setIcon(new javax.swing.ImageIcon("src//main//java//pi_1sem//images//usuario_adm_5.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(retornaNome());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(String.format(""+Usuario.usuarioLogado.getId()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 599, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("src//main//java//pi_1sem//images//tela_de_editar_4.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 570, 360));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setText("Editar pergunta");

        jLabel5.setIcon(new javax.swing.ImageIcon("src//main//java//pi_1sem//images//rd_sem_fundo.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 36)); // NOI18N
        jLabel8.setText("Adicionar Pergunta");

        jLabel9.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel9.setText("Bem-vindo ao painel de controle. Adcione sua pergunta !!! ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        adicionarPerguntaButton.setBackground(new java.awt.Color(0, 102, 255));
        adicionarPerguntaButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        adicionarPerguntaButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarPerguntaButton.setText("Adicionar");
        adicionarPerguntaButton.setBorder(null);
        adicionarPerguntaButton.setFocusPainted(false);
        adicionarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPerguntaButtonActionPerformed(evt);
            }
        });
        voltarButton.setBackground(new java.awt.Color(146, 198, 243));
        voltarButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 829, Short.MAX_VALUE)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1200, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 630, 330));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        var resposta= JOptionPane.showConfirmDialog(null, "Deseja adicionar a pergunta e suas alternativas?" , "Tem certeza disso?",JOptionPane.OK_CANCEL_OPTION );

        if(resposta == JOptionPane.OK_OPTION){
            String [] perguntaEAlternativas= {
                perguntaTextField.getText(),
                alternativaATextField.getText(),
                alternativaBTextField.getText(),
                alternativaCTextField.getText(),
                alternativaDTextField.getText()
            };
    
            for (String i: perguntaEAlternativas){
                if(i.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de adicionar a pergunta");
                    return;
                }
            }

            List<Boolean> opcoesAlternativaCorreta = Arrays.asList(alternativaARadioButton.isSelected(), alternativaBRadioButton.isSelected(),alternativaCRadioButton.isSelected(),alternativaDRadioButton.isSelected());
            
            var temVerdadiro= false;
            for(boolean i : opcoesAlternativaCorreta){
                if (i == true){
                    temVerdadiro= true;
                }
            }

            if(temVerdadiro == false){
                JOptionPane.showMessageDialog(null, "Selecione uma alternativa para ser a correta, clique na bolinha");
                return;
            }
            
            var materia = new Materia((String)escolherMateriaComboBox.getSelectedItem());
            materia.atribuiId();
        
            var nivel= (String) escolherDificuldadeComboBox.getSelectedItem();
        
            var pergunta = new Pergunta(perguntaEAlternativas[0], materia, nivel);
    
            try{
                var perguntaDao= new PerguntaDAO();
                perguntaDao.adicionarPergunta(pergunta);
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao adicionar pergunta");
            }
    
            String[] letras= {"A", "B", "C", "D"};
            List<Alternativa> alternativas = new ArrayList<>();
    
            try{
                var alternativaDao= new AlternativaDAO();
        
                for (int i = 1; i < 5; i++){
                    var novaAlternativa= new Alternativa(letras[i-1], perguntaEAlternativas[i]);
                    alternativas.add(novaAlternativa); 
                }
                alternativaDao.adicionarAlternativa(alternativas);
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao adicionar alternativas");
            }    
    
            List<PerguntaAlternativa> perguntaAlternativas = new ArrayList<>();
            for (int i = 0; i < 4; i++){
                var perguntaAlternativa = new PerguntaAlternativa(pergunta, alternativas.get(i), opcoesAlternativaCorreta.get(i));
                perguntaAlternativas.add(perguntaAlternativa);
            }
            try{
                var perguntaAlternativaDao= new PerguntaAlternativaDAO();
                perguntaAlternativaDao.adicionarPerguntaAlternativa(perguntaAlternativas);
                JOptionPane.showMessageDialog(null, "Pergunta adicionada com sucesso");
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao adicionar pergunta alternativa");
            }
        }
    }

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//
        new TelaEdicaoPergunta().setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdcionarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdcionarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdcionarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdcionarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdcionarPergunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup alterantivasButtonGroup;
    private javax.swing.JComboBox<String> escolherMateriaComboBox;
    private javax.swing.JComboBox<String> escolherDificuldadeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton alternativaARadioButton;
    private javax.swing.JTextField alternativaATextField;
    private javax.swing.JRadioButton alternativaBRadioButton;
    private javax.swing.JTextField alternativaBTextField;
    private javax.swing.JRadioButton alternativaCRadioButton;
    private javax.swing.JTextField alternativaCTextField;
    private javax.swing.JRadioButton alternativaDRadioButton;
    private javax.swing.JTextField alternativaDTextField;
    private javax.swing.JTextField perguntaTextField;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton adicionarPerguntaButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
    
    private String retornaNome(){
        try {
            var usuarioDao= new UsuarioDAO();
            var usuarioNome= usuarioDao.pegarNome();

            return usuarioNome;
        } 
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao retornat nome de usuario");
            return null;
        }
    }
}
