/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi_1sem.screens;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

import pi_1sem.modelo.participantes.Aluno;
import pi_1sem.persistencia.usuarios.AlunoDAO;


/**
 *
 * @author charl
 */
public class UsuarioEditar extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public UsuarioEditar() {
        initComponents();
        listarAlunos();
        capturarAltercoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alunosTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        adicionarAlunoButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        excluirButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(71, 71, 215));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Poliedro");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alunos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        alunosTable.setShowGrid(true);
        alunosTable.setGridColor(java.awt.Color.GRAY);
        alunosTable.setRowHeight(30);
        alunosTable.setBackground(new java.awt.Color(204, 204, 204));
        alunosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Aluno", "Nome", "E-mail", "Senha"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        });
        for (int i = 1; i < alunosTable.getColumnCount(); i++) {
            javax.swing.table.TableColumn column = alunosTable.getColumnModel().getColumn(i);
            if (column.getCellEditor() instanceof javax.swing.DefaultCellEditor) {
                ((javax.swing.DefaultCellEditor) column.getCellEditor()).setClickCountToStart(2);
            }
        }
        jScrollPane1.setViewportView(alunosTable);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        jLabel4.setText("Nome :");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        jLabel5.setText("E-mail :");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        jLabel6.setText("Senha : ");

        adicionarAlunoButton.setBackground(new java.awt.Color(71, 71, 215));
        adicionarAlunoButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adicionarAlunoButton.setForeground(new java.awt.Color(255, 255, 255));
        adicionarAlunoButton.setText("+    Adicionar Aluno ");
        adicionarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAlunoButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("Editar Aluno ");

        excluirButton.setBackground(new java.awt.Color(71, 71, 215));
        excluirButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        excluirButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirButton.setText("Excluir ");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        voltarButton.setBackground(new java.awt.Color(255, 51, 51));
        voltarButton.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setText("Voltar ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 814, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(adicionarAlunoButton)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\charl\\Downloads\\PI Mauá\\usuario adm 2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        var resposta= JOptionPane.showConfirmDialog(null, "Deseja adicionar o Aluno?", "Tem certeza disso?", JOptionPane.OK_CANCEL_OPTION);
        if(resposta == JOptionPane.OK_OPTION){
            String [] campos={
                nomeTextField.getText(),
                emailTextField.getText(),
                senhaTextField.getText()
            };
            for (int i= 0; i < campos.length; i++) {
                if(campos[i].isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
                    return;
                }
                if(i == 1 && !campos[i].contains("@")){
                    JOptionPane.showMessageDialog(null, "Email inválido!");
                    return;
                }
                if(i == 2 && campos[i].length()<8){
                    JOptionPane.showMessageDialog(null, "A senha deve ter no mínimo 8 caracteres!");
                    return;
                }
            }
            try{
                var aluno= new Aluno(campos[0], campos[1], campos[2]);
                var alunoDAO= new AlunoDAO();
                alunoDAO.cadastrar(aluno);
    
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!");
                listarAlunos();
            
                nomeTextField.setText("");                
                emailTextField.setText("");
                senhaTextField.setText("");
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar o aluno");
            } 
        }
    }//GEN-LAST:event_adicionarAlunoButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        var resposta= JOptionPane.showConfirmDialog(null, "Deseja excluir o Aluno?", "Tem certeza disso?", JOptionPane.OK_CANCEL_OPTION);

        if(resposta == JOptionPane.OK_OPTION){
            try {
                int idExcluir= pegarCampoId();
                var alunoDAO = new AlunoDAO();
                alunoDAO.remover(idExcluir);
                listarAlunos();
    
                JOptionPane.showMessageDialog(this, "Aluno excluido!");
            } 
            catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao excluir o aluno!");
            }

        }
    }
    //GEN-LAST:event_excluirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UsuarioEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAlunoButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton excluirButton;
    private javax.swing.JButton voltarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JTable alunosTable;
    // End of variables declaration//GEN-END:variables

    private void listarAlunos() {
        try {
            var alunoDAO= new AlunoDAO();
            DefaultTableModel model = (DefaultTableModel) alunosTable.getModel();
            model.setNumRows(0);


            ArrayList<Aluno> alunos = alunoDAO.listar();

            for (Aluno i: alunos) {
                model.addRow(new Object[]{
                    i.getId(),
                    i.getNome(),
                    i.getEmail(),
                    i.getSenha()
                });
            }   
        } 
        
        catch (Exception e) {
           e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao listar alunos");
        }
    }
    private Integer pegarCampoId(){
        int linhaSelecionada = alunosTable.getSelectedRow();   
        int idSelecionado= Integer.parseInt(alunosTable.getModel().getValueAt(linhaSelecionada, 0).toString());

        return idSelecionado;
    }

    private void capturarAltercoes(){
        var model = (DefaultTableModel) alunosTable.getModel();
    
    // Adiciona um listener único (evita múltiplas instâncias)
    model.removeTableModelListener(this::handleTableUpdate);
    model.addTableModelListener(this::handleTableUpdate);
    }

    private void handleTableUpdate(TableModelEvent e) {
        if (e.getType() != TableModelEvent.UPDATE || e.getColumn() < 1) return;
        
        int row = e.getFirstRow();
        int col = e.getColumn();
        
        if (row < 0 || row >= alunosTable.getRowCount()) return;
    
        var valorAlterado = alunosTable.getModel().getValueAt(row, col).toString();
        var id = Integer.parseInt(alunosTable.getModel().getValueAt(row, 0).toString());

        if (col == 1) {
            try{
                AlunoDAO alunoDAO = new AlunoDAO();
                alunoDAO.atualizarNome(valorAlterado, id);

                JOptionPane.showMessageDialog(null, "O nome foi alterado com sucesso");
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao alterar o nome");
            }
        }
        if (col == 2) {
            if(!valorAlterado.contains("@")){
                JOptionPane.showMessageDialog(null, "ERRO! O email deve conter @");
                return;
            }
            try{
                AlunoDAO alunoDAO = new AlunoDAO();
                alunoDAO.atualizarEmail(valorAlterado, id);

                JOptionPane.showMessageDialog(null, "O email foi alterado com sucesso");
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao alterar o email");
            }
        }
        if (col == 3) {
            if(valorAlterado.length() < 8){
                JOptionPane.showMessageDialog(null, "ERRO! A senha deve conter no mínimo 8 caracteres");
                return;
            }
            try{
                AlunoDAO alunoDAO = new AlunoDAO();
                alunoDAO.atualizarSenha(valorAlterado, id);
                JOptionPane.showMessageDialog(null, "A senha foi alterada com sucesso");
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao alterar a senha");
            }
        }
    }
}